/**
 * @file evenFibonacciNum.cpp
 * @author kanika Garg
 * @brief 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * @version 0.1
 * @date 2022-09-11
 * 
 * @copyright Copyright (c) 2022
 * 
 */

#include <iostream>
#include <cmath>
int main(){
    long long fib1 = 1;
    long long fib2 = 2;
    long long sum = 2;
    long long num = fib1+fib2;
    const long fourMillion = pow(10,6)*4;
    while (num < fourMillion){
        if (num % 2 == 0){
            sum+=num;
        }
        fib1 = fib2;
        fib2 = num;
        num += fib1;
    }
    std::cout<<sum<<std::endl;
    return 0;
}